// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
/// import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXTG90hBRmSuj3YylLAIU9rOOm83cwyXs',
    appId: '1:617832382902:web:92312d2545965f86034117',
    messagingSenderId: '617832382902',
    projectId: 'currency-13d9b',
    authDomain: 'currency-13d9b.firebaseapp.com',
    storageBucket: 'currency-13d9b.appspot.com',
    measurementId: 'G-5CL3R4TNRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeeXVIW-YvRMU7M2l5xJgeHFBN7x1riqY',
    appId: '1:617832382902:android:616fdb141fb52526034117',
    messagingSenderId: '617832382902',
    projectId: 'currency-13d9b',
    storageBucket: 'currency-13d9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALJVifIg-b6PA_M_PLXzthKvw9nPBxkcY',
    appId: '1:617832382902:ios:e3dbcd52a9c7c85f034117',
    messagingSenderId: '617832382902',
    projectId: 'currency-13d9b',
    storageBucket: 'currency-13d9b.appspot.com',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALJVifIg-b6PA_M_PLXzthKvw9nPBxkcY',
    appId: '1:617832382902:ios:c879647d5338e0e3034117',
    messagingSenderId: '617832382902',
    projectId: 'currency-13d9b',
    storageBucket: 'currency-13d9b.appspot.com',
    iosBundleId: 'com.example.authFirebase.RunnerTests',
  );
}
